MIN_HORIZONTAL_SEPARATION = 5.0 # NM (nautical miles)
MIN_VERTICAL_SEPARATION = 1000 # FEET

COLLISION_HORIZONTAL_SEPARATION = 0.5 # NM
COLLISION_VERTICAL_SEPARATION = 200 # FEET

UPDATE_TIME = 1.0 # SECONDS
TOTAL_TIME = 60 # SECONDS